### PR TITLE
Update README with Basic Usage information

### PR DESCRIPTION
**Pull request by ItzFireable**

### CODE REVIEW

**Comment by ItzFireable** [comment]
thanks i love misclicking

**Comment by MrSiliconGuy** [comment]
Oh wow I didn't think anyone would actually use this.
Thanks

**Comment by MrSiliconGuy** [comment]
Guess I'll add some actual documentation then

**Comment by ItzFireable** [comment]
Yeah, I actually found this better than commando (which is really outdated), may as well help with it 👀

**Pull request merged**
